/**
 * Sync Orchestration
 *
 * Coordinates the full conversation sync workflow:
 * 1. Load state
 * 2. Scan for conversation files
 * 3. Determine which need processing
 * 4. Process each file
 * 5. Update and save state
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { preprocessJsonl } from "./preprocessor.js";
import { type ConversationFile, getDefaultConversationsDir, scanConversationDirectory } from "./scanner.js";
import {
  getConversationState,
  loadSyncState,
  needsProcessing,
  saveSyncState,
  updateConversationState,
} from "./state.js";
import { summarizeConversation } from "./summarizer.js";
import type { ConversationSummary, SessionMetadata, SyncOptions, SyncResult, SyncState } from "./types.js";

/**
 * Find the monorepo root by looking for pnpm-workspace.yaml.
 */
function findRepoRoot(): string {
  let dir = process.cwd();
  while (dir !== path.dirname(dir)) {
    if (fs.existsSync(path.join(dir, "pnpm-workspace.yaml"))) {
      return dir;
    }
    dir = path.dirname(dir);
  }
  return process.cwd();
}

/**
 * Get the knowledge directory from env or default.
 */
function getDefaultKnowledgeDir(): string {
  return process.env.KAHUNA_KNOWLEDGE_DIR || path.join(findRepoRoot(), "knowledge");
}

/**
 * Format a summary as markdown with frontmatter.
 */
function formatSummaryAsMarkdown(
  summary: ConversationSummary,
  metadata: SessionMetadata,
  sourcePath: string,
  chunked: boolean,
  chunkCount?: number
): string {
  const date = metadata.timestamp
    ? new Date(metadata.timestamp).toISOString().split("T")[0]
    : new Date().toISOString().split("T")[0];

  const lines: string[] = [
    "---",
    `title: "${summary.title.replace(/"/g, '\\"')}"`,
    `session_id: ${metadata.sessionId}`,
    `source: ${sourcePath}`,
    `date: ${date}`,
    `task_type: ${summary.taskType}`,
    `outcome: ${summary.outcome}`,
    `confidence: ${summary.confidence}`,
    `chunked: ${chunked}`,
  ];

  if (chunked && chunkCount) {
    lines.push(`chunk_count: ${chunkCount}`);
  }

  lines.push("---", "", `# ${summary.title}`, "", "## Summary", "", summary.summary, "", "## Decisions Made", "");

  if (summary.decisions.length === 0) {
    lines.push("- None recorded");
  } else {
    summary.decisions.forEach((d, i) => {
      lines.push(`${i + 1}. **${d.decision}**${d.rationale ? ` - ${d.rationale}` : ""}`);
    });
  }

  lines.push("", "## Files Created", "");

  if (summary.filesCreated.length === 0) {
    lines.push("- None");
  } else {
    for (const f of summary.filesCreated) {
      lines.push(`- \`${f}\``);
    }
  }

  lines.push("", "## Files Modified", "");

  if (summary.filesModified.length === 0) {
    lines.push("- None");
  } else {
    for (const f of summary.filesModified) {
      lines.push(`- \`${f}\``);
    }
  }

  lines.push("", "---", "*Generated by Kahuna conversation processor*", `*Source: ${sourcePath}*`);

  return lines.join("\n");
}

/**
 * Write summary to the knowledge base.
 */
function writeSummary(content: string, sessionId: string, knowledgeDir: string): string {
  const outputPath = path.join(knowledgeDir, "conversations", `${sessionId}.md`);
  const dir = path.dirname(outputPath);

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputPath, content, "utf-8");
  return outputPath;
}

/**
 * Process a single conversation file.
 *
 * @returns Object containing output path and chunking info
 */
async function processConversationFile(
  file: ConversationFile,
  knowledgeDir: string
): Promise<{ outputPath: string; chunked: boolean; chunkCount?: number }> {
  // Stage 1: Preprocess JSONL to clean markdown
  const { markdown, metadata } = preprocessJsonl(file.path);

  // Stage 2: Summarize with LLM
  const summary = await summarizeConversation(markdown);

  // Determine if chunking was used (check if markdown was large)
  const estimatedTokens = Math.ceil(markdown.length / 4);
  const chunked = estimatedTokens > 100000;
  const chunkCount = chunked ? Math.ceil(estimatedTokens / 100000) : undefined;

  // Stage 3: Format and write output
  const outputContent = formatSummaryAsMarkdown(summary, metadata, file.path, chunked, chunkCount);
  const outputPath = writeSummary(outputContent, file.sessionId, knowledgeDir);

  return { outputPath, chunked, chunkCount };
}

/**
 * Categorize files into processing buckets based on state comparison.
 */
function categorizeFiles(
  files: ConversationFile[],
  state: SyncState,
  force: boolean
): {
  toProcess: Array<ConversationFile & { isNew: boolean }>;
  toSkip: ConversationFile[];
} {
  const toProcess: Array<ConversationFile & { isNew: boolean }> = [];
  const toSkip: ConversationFile[] = [];

  for (const file of files) {
    if (force) {
      // Force mode: process everything
      const isNew = !getConversationState(state, file.sessionId);
      toProcess.push({ ...file, isNew });
    } else if (needsProcessing(state, file.sessionId, file.hash)) {
      // Normal mode: only process new or changed
      const isNew = !getConversationState(state, file.sessionId);
      toProcess.push({ ...file, isNew });
    } else {
      // Already processed and unchanged
      toSkip.push(file);
    }
  }

  return { toProcess, toSkip };
}

/**
 * Main sync function - coordinates the full workflow.
 *
 * @param options - Sync options (force, directory overrides)
 * @returns SyncResult with counts and any errors
 */
export async function syncConversations(options: SyncOptions = {}): Promise<SyncResult> {
  const startTime = Date.now();
  const errors: string[] = [];

  // Resolve directories
  const conversationsDir = options.conversationsDir || getDefaultConversationsDir();
  const knowledgeDir = options.knowledgeDir || getDefaultKnowledgeDir();
  const force = options.force || false;

  console.log(`Scanning for conversations in: ${conversationsDir}`);
  console.log(`Output directory: ${knowledgeDir}`);

  // Load current state
  const state = loadSyncState(knowledgeDir);

  // Scan for conversation files
  const files = scanConversationDirectory(conversationsDir);
  console.log(`Found ${files.length} conversation file(s)`);

  if (files.length === 0) {
    return {
      success: true,
      processed: 0,
      updated: 0,
      skipped: 0,
      failed: 0,
      duration_ms: Date.now() - startTime,
    };
  }

  // Categorize files
  const { toProcess, toSkip } = categorizeFiles(files, state, force);

  // Count new vs updated
  const newCount = toProcess.filter((f) => f.isNew).length;
  const updateCount = toProcess.filter((f) => !f.isNew).length;

  console.log(`To process: ${toProcess.length} (${newCount} new, ${updateCount} changed)`);
  console.log(`To skip: ${toSkip.length} (already current)`);

  // Process files
  let processed = 0;
  let updated = 0;
  let failed = 0;

  for (const file of toProcess) {
    try {
      console.log(`Processing: ${file.sessionId}...`);

      const result = await processConversationFile(file, knowledgeDir);

      // Update state
      updateConversationState(state, file.sessionId, {
        sourcePath: file.path,
        sourceHash: file.hash,
        outputPath: result.outputPath,
        processedAt: new Date().toISOString(),
        chunked: result.chunked,
        chunkCount: result.chunkCount,
      });

      if (file.isNew) {
        processed++;
      } else {
        updated++;
      }

      console.log(`  ✓ Saved to: ${result.outputPath}`);
    } catch (error) {
      failed++;
      const errorMsg = `${file.sessionId}: ${error instanceof Error ? error.message : String(error)}`;
      errors.push(errorMsg);
      console.error(`  ✗ Failed: ${errorMsg}`);
    }
  }

  // Save updated state
  saveSyncState(knowledgeDir, state);

  const result: SyncResult = {
    success: failed === 0,
    processed,
    updated,
    skipped: toSkip.length,
    failed,
    duration_ms: Date.now() - startTime,
  };

  if (errors.length > 0) {
    result.errors = errors;
  }

  return result;
}
