/**
 * CLI for processing Claude Code conversation logs.
 *
 * Usage:
 *   pnpm --filter @kahuna/mcp cli process <jsonl-path>
 *   pnpm --filter @kahuna/mcp cli process --project <claude-project-path>
 *   pnpm --filter @kahuna/mcp cli process --latest <claude-project-path>
 */

// Load environment variables from .env file
import { config } from "dotenv";
config();

import * as fs from "node:fs";
import * as path from "node:path";
import { Command } from "commander";
import { preprocessJsonl } from "./processing/preprocessor.js";
import { summarizeConversation } from "./processing/summarizer.js";
import type { ConversationSummary, SessionMetadata } from "./processing/types.js";

const program = new Command();

/**
 * Format a summary as markdown with frontmatter.
 */
function formatSummaryAsMarkdown(
  summary: ConversationSummary,
  metadata: SessionMetadata,
  sourcePath: string
): string {
  const date = metadata.timestamp
    ? new Date(metadata.timestamp).toISOString().split("T")[0]
    : new Date().toISOString().split("T")[0];

  const lines: string[] = [
    "---",
    `title: "${summary.title.replace(/"/g, '\\"')}"`,
    `session_id: ${metadata.sessionId}`,
    `source: ${sourcePath}`,
    `date: ${date}`,
    `task_type: ${summary.taskType}`,
    `outcome: ${summary.outcome}`,
    `confidence: ${summary.confidence}`,
    `chunked: false`,
    "---",
    "",
    `# ${summary.title}`,
    "",
    "## Summary",
    "",
    summary.summary,
    "",
    "## Decisions Made",
    "",
  ];

  if (summary.decisions.length === 0) {
    lines.push("- None recorded");
  } else {
    summary.decisions.forEach((d, i) => {
      lines.push(`${i + 1}. **${d.decision}**${d.rationale ? ` - ${d.rationale}` : ""}`);
    });
  }

  lines.push("");
  lines.push("## Files Created");
  lines.push("");

  if (summary.filesCreated.length === 0) {
    lines.push("- None");
  } else {
    summary.filesCreated.forEach((f) => lines.push(`- \`${f}\``));
  }

  lines.push("");
  lines.push("## Files Modified");
  lines.push("");

  if (summary.filesModified.length === 0) {
    lines.push("- None");
  } else {
    summary.filesModified.forEach((f) => lines.push(`- \`${f}\``));
  }

  lines.push("");
  lines.push("---");
  lines.push("*Generated by Kahuna conversation processor*");
  lines.push(`*Source: ${sourcePath}*`);

  return lines.join("\n");
}

/**
 * Write summary to the knowledge base.
 */
function writeSummary(content: string, sessionId: string, outputDir: string): string {
  const outputPath = path.join(outputDir, "conversations", `${sessionId}.md`);
  const dir = path.dirname(outputPath);

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputPath, content, "utf-8");
  return outputPath;
}

/**
 * Find the monorepo root by looking for pnpm-workspace.yaml.
 */
function findRepoRoot(): string {
  let dir = process.cwd();
  while (dir !== path.dirname(dir)) {
    if (fs.existsSync(path.join(dir, "pnpm-workspace.yaml"))) {
      return dir;
    }
    dir = path.dirname(dir);
  }
  // Fallback to cwd if not found
  return process.cwd();
}

/**
 * Get the knowledge directory from env or default.
 */
function getKnowledgeDir(): string {
  return process.env.KAHUNA_KNOWLEDGE_DIR || path.join(findRepoRoot(), "knowledge");
}

/**
 * Process a single JSONL file.
 */
async function processSingleFile(
  jsonlPath: string,
  options: { dryRun?: boolean; outputClean?: boolean }
): Promise<void> {
  const absolutePath = path.resolve(jsonlPath);

  if (!fs.existsSync(absolutePath)) {
    console.error(`Error: File not found: ${absolutePath}`);
    process.exit(1);
  }

  console.log(`Processing: ${absolutePath}`);

  // Stage 1: Preprocess JSONL to clean markdown
  const { markdown, metadata } = preprocessJsonl(absolutePath);

  if (options.outputClean) {
    const cleanPath = absolutePath.replace(/\.jsonl$/, ".clean.md");
    fs.writeFileSync(cleanPath, markdown, "utf-8");
    console.log(`Clean markdown saved to: ${cleanPath}`);
  }

  if (options.dryRun) {
    console.log("\n=== DRY RUN - Preprocessed Markdown ===\n");
    console.log(markdown.slice(0, 2000));
    if (markdown.length > 2000) {
      console.log(`\n... (${markdown.length - 2000} more characters)`);
    }
    console.log("\n=== Metadata ===");
    console.log(JSON.stringify(metadata, null, 2));
    return;
  }

  // Check for API key
  if (!process.env.ANTHROPIC_API_KEY) {
    console.error("Error: ANTHROPIC_API_KEY environment variable is required");
    console.error("Set it in your environment or .env file");
    process.exit(1);
  }

  // Stage 2: Summarize with LLM
  console.log("Summarizing conversation...");
  const summary = await summarizeConversation(markdown);

  // Stage 3: Write output
  const outputContent = formatSummaryAsMarkdown(summary, metadata, absolutePath);
  const knowledgeDir = getKnowledgeDir();
  const outputPath = writeSummary(outputContent, metadata.sessionId, knowledgeDir);

  console.log(`Summary written to: ${outputPath}`);
}

/**
 * Find all JSONL files in a Claude project directory.
 */
function findJsonlFiles(projectPath: string): string[] {
  const absolutePath = path.resolve(projectPath);

  if (!fs.existsSync(absolutePath)) {
    console.error(`Error: Directory not found: ${absolutePath}`);
    process.exit(1);
  }

  const files = fs.readdirSync(absolutePath);
  return files
    .filter((f) => f.endsWith(".jsonl"))
    .map((f) => path.join(absolutePath, f))
    .sort((a, b) => {
      // Sort by modification time, newest first
      const statA = fs.statSync(a);
      const statB = fs.statSync(b);
      return statB.mtimeMs - statA.mtimeMs;
    });
}

// CLI setup
program
  .name("kahuna-cli")
  .description("Process Claude Code conversation logs into structured summaries")
  .version("0.1.0");

program
  .command("process")
  .description("Process conversation log(s)")
  .argument("[jsonl-path]", "Path to a single JSONL file")
  .option("--project <path>", "Process all JSONL files in a Claude project directory")
  .option("--latest <path>", "Process only the most recent JSONL in a directory")
  .option("--dry-run", "Show preprocessing output without calling the LLM")
  .option("--output-clean", "Also save the clean markdown file for debugging")
  .action(async (jsonlPath: string | undefined, options) => {
    try {
      if (options.project) {
        const files = findJsonlFiles(options.project);
        if (files.length === 0) {
          console.log("No JSONL files found in:", options.project);
          return;
        }
        console.log(`Found ${files.length} JSONL files`);
        for (const file of files) {
          await processSingleFile(file, options);
          console.log("");
        }
      } else if (options.latest) {
        const files = findJsonlFiles(options.latest);
        if (files.length === 0) {
          console.log("No JSONL files found in:", options.latest);
          return;
        }
        // Files are sorted newest first
        await processSingleFile(files[0], options);
      } else if (jsonlPath) {
        await processSingleFile(jsonlPath, options);
      } else {
        console.error("Error: Provide a JSONL path or use --project/--latest");
        process.exit(1);
      }
    } catch (error) {
      console.error("Processing failed:", error);
      process.exit(1);
    }
  });

program.parse();
